In [56]:
import numpy as np
import pandas as pd  
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

In [57]:
home_price = pd.read_csv("homeprices.csv")
home_price

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [58]:
home_price.bedrooms.median()

4.0

In [59]:
home_price["bedrooms"]=home_price["bedrooms"].fillna(home_price.bedrooms.median())

In [60]:
home_price.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [61]:
lr=LinearRegression()
lr.fit(home_price.drop("price",axis=1),home_price.price)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [62]:
lr.predict([[3000, 3, 40]])

array([498408.25158031])

In [63]:
lr.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [64]:
lr.intercept_

221323.00186540408

In [65]:
#exercise

In [66]:
hiring=pd.read_csv("hiring.csv")

In [67]:
hiring

experience  test_score  interview_score(out of 10)  salary
0        NaN         8.0                           9   50000
1        NaN         8.0                           6   45000
2       five         6.0                           7   60000
3        two        10.0                          10   65000
4      seven         9.0                           6   70000
5      three         7.0                          10   62000
6        ten         NaN                           7   72000
7     eleven         7.0                           8   80000

In [68]:
from word2number import w2n

In [69]:
hiring["experience"]=hiring["experience"].fillna("zero")

In [87]:
hiring["experience"]=hiring["experience"].apply(w2n.word_to_num)
hiring.test_score.median()

ValueError: Type of input is not string! Please enter a valid number word (eg. 'two million twenty three thousand and forty nine')

In [84]:
hiring["test_score"]=hiring["test_score"].fillna(hiring.test_score.median())

In [83]:
hr=LinearRegression()
hr.fit(hiring.drop("salary",axis=1),hiring.salary)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [82]:
hr.predict([[2,9,6]])

array([53205.96797671])

In [77]:
hr.predict([[12,10,10]])

array([92002.18340611])

In [88]:
hiring

experience  test_score  interview_score(out of 10)  salary
0           0         8.0                           9   50000
1           0         8.0                           6   45000
2           5         6.0                           7   60000
3           2        10.0                          10   65000
4           7         9.0                           6   70000
5           3         7.0                          10   62000
6          10         8.0                           7   72000
7          11         7.0                           8   80000